/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { VotingSystem } from './VotingSystem.js';
export * as factories from './factories/index.js';
export { VotingSystem__factory } from './factories/VotingSystem__factory.js';