/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  

  export interface VotingSystemInterface extends Interface {
    getFunction(nameOrSignature: "ACTIVE" | "CLOSED" | "NOT_STARTED" | "addCandidate" | "admin" | "createElection" | "currentElectionId" | "electionCount" | "elections" | "endElection" | "getCandidate" | "getCandidateCount" | "getCurrentElection" | "getElection" | "getElectionStatus" | "getVoterChoice" | "hasVoted" | "isRegisteredVoter" | "registerVoter" | "startElection" | "vote"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "CandidateAdded" | "ElectionCreated" | "ElectionEnded" | "ElectionStarted" | "VoteCast" | "VoterRegistered"): EventFragment;

    encodeFunctionData(functionFragment: 'ACTIVE', values?: undefined): string;
encodeFunctionData(functionFragment: 'CLOSED', values?: undefined): string;
encodeFunctionData(functionFragment: 'NOT_STARTED', values?: undefined): string;
encodeFunctionData(functionFragment: 'addCandidate', values: [string, string]): string;
encodeFunctionData(functionFragment: 'admin', values?: undefined): string;
encodeFunctionData(functionFragment: 'createElection', values: [string]): string;
encodeFunctionData(functionFragment: 'currentElectionId', values?: undefined): string;
encodeFunctionData(functionFragment: 'electionCount', values?: undefined): string;
encodeFunctionData(functionFragment: 'elections', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'endElection', values?: undefined): string;
encodeFunctionData(functionFragment: 'getCandidate', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getCandidateCount', values?: undefined): string;
encodeFunctionData(functionFragment: 'getCurrentElection', values?: undefined): string;
encodeFunctionData(functionFragment: 'getElection', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getElectionStatus', values?: undefined): string;
encodeFunctionData(functionFragment: 'getVoterChoice', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'hasVoted', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'isRegisteredVoter', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'registerVoter', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'startElection', values?: undefined): string;
encodeFunctionData(functionFragment: 'vote', values: [BigNumberish]): string;

    decodeFunctionResult(functionFragment: 'ACTIVE', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'CLOSED', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'NOT_STARTED', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'addCandidate', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'admin', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'createElection', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'currentElectionId', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'electionCount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'elections', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'endElection', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getCandidate', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getCandidateCount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getCurrentElection', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getElection', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getElectionStatus', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getVoterChoice', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'hasVoted', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'isRegisteredVoter', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'registerVoter', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'startElection', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'vote', data: BytesLike): Result;
  }

  
    export namespace CandidateAddedEvent {
      export type InputTuple = [electionId: BigNumberish, candidateId: BigNumberish, name: string, party: string];
      export type OutputTuple = [electionId: bigint, candidateId: bigint, name: string, party: string];
      export interface OutputObject {electionId: bigint, candidateId: bigint, name: string, party: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ElectionCreatedEvent {
      export type InputTuple = [electionId: BigNumberish, name: string];
      export type OutputTuple = [electionId: bigint, name: string];
      export interface OutputObject {electionId: bigint, name: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ElectionEndedEvent {
      export type InputTuple = [electionId: BigNumberish];
      export type OutputTuple = [electionId: bigint];
      export interface OutputObject {electionId: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ElectionStartedEvent {
      export type InputTuple = [electionId: BigNumberish];
      export type OutputTuple = [electionId: bigint];
      export interface OutputObject {electionId: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace VoteCastEvent {
      export type InputTuple = [electionId: BigNumberish, voter: AddressLike, candidateId: BigNumberish];
      export type OutputTuple = [electionId: bigint, voter: string, candidateId: bigint];
      export interface OutputObject {electionId: bigint, voter: string, candidateId: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace VoterRegisteredEvent {
      export type InputTuple = [electionId: BigNumberish, voter: AddressLike];
      export type OutputTuple = [electionId: bigint, voter: string];
      export interface OutputObject {electionId: bigint, voter: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface VotingSystem extends BaseContract {
    
    connect(runner?: ContractRunner | null): VotingSystem;
    waitForDeployment(): Promise<this>;

    interface: VotingSystemInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    ACTIVE: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    CLOSED: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    NOT_STARTED: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    addCandidate: TypedContractMethod<
      [_name: string, _party: string, ],
      [void],
      'nonpayable'
    >
    

    
    admin: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    createElection: TypedContractMethod<
      [_name: string, ],
      [bigint],
      'nonpayable'
    >
    

    
    currentElectionId: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    electionCount: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    elections: TypedContractMethod<
      [arg0: BigNumberish, ],
      [[bigint, string, bigint, bigint] & {id: bigint, name: string, status: bigint, candidateCount: bigint }],
      'view'
    >
    

    
    endElection: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    getCandidate: TypedContractMethod<
      [_id: BigNumberish, ],
      [[bigint, string, string, bigint] & {id: bigint, name: string, party: string, voteCount: bigint }],
      'view'
    >
    

    
    getCandidateCount: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    getCurrentElection: TypedContractMethod<
      [],
      [[bigint, string, bigint, bigint] & {id: bigint, name: string, status: bigint, candidateCount: bigint }],
      'view'
    >
    

    
    getElection: TypedContractMethod<
      [_electionId: BigNumberish, ],
      [[bigint, string, bigint, bigint] & {id: bigint, name: string, status: bigint, candidateCount: bigint }],
      'view'
    >
    

    
    getElectionStatus: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    getVoterChoice: TypedContractMethod<
      [_voter: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    hasVoted: TypedContractMethod<
      [_voter: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    isRegisteredVoter: TypedContractMethod<
      [_voter: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    registerVoter: TypedContractMethod<
      [_voter: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    startElection: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    vote: TypedContractMethod<
      [_candidateId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'ACTIVE'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'CLOSED'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'NOT_STARTED'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'addCandidate'): TypedContractMethod<
      [_name: string, _party: string, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'admin'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'createElection'): TypedContractMethod<
      [_name: string, ],
      [bigint],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'currentElectionId'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'electionCount'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'elections'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [[bigint, string, bigint, bigint] & {id: bigint, name: string, status: bigint, candidateCount: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'endElection'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'getCandidate'): TypedContractMethod<
      [_id: BigNumberish, ],
      [[bigint, string, string, bigint] & {id: bigint, name: string, party: string, voteCount: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'getCandidateCount'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getCurrentElection'): TypedContractMethod<
      [],
      [[bigint, string, bigint, bigint] & {id: bigint, name: string, status: bigint, candidateCount: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'getElection'): TypedContractMethod<
      [_electionId: BigNumberish, ],
      [[bigint, string, bigint, bigint] & {id: bigint, name: string, status: bigint, candidateCount: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'getElectionStatus'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getVoterChoice'): TypedContractMethod<
      [_voter: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'hasVoted'): TypedContractMethod<
      [_voter: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'isRegisteredVoter'): TypedContractMethod<
      [_voter: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'registerVoter'): TypedContractMethod<
      [_voter: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'startElection'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'vote'): TypedContractMethod<
      [_candidateId: BigNumberish, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'CandidateAdded'): TypedContractEvent<CandidateAddedEvent.InputTuple, CandidateAddedEvent.OutputTuple, CandidateAddedEvent.OutputObject>;
getEvent(key: 'ElectionCreated'): TypedContractEvent<ElectionCreatedEvent.InputTuple, ElectionCreatedEvent.OutputTuple, ElectionCreatedEvent.OutputObject>;
getEvent(key: 'ElectionEnded'): TypedContractEvent<ElectionEndedEvent.InputTuple, ElectionEndedEvent.OutputTuple, ElectionEndedEvent.OutputObject>;
getEvent(key: 'ElectionStarted'): TypedContractEvent<ElectionStartedEvent.InputTuple, ElectionStartedEvent.OutputTuple, ElectionStartedEvent.OutputObject>;
getEvent(key: 'VoteCast'): TypedContractEvent<VoteCastEvent.InputTuple, VoteCastEvent.OutputTuple, VoteCastEvent.OutputObject>;
getEvent(key: 'VoterRegistered'): TypedContractEvent<VoterRegisteredEvent.InputTuple, VoterRegisteredEvent.OutputTuple, VoterRegisteredEvent.OutputObject>;

    filters: {
      
      'CandidateAdded(uint256,uint256,string,string)': TypedContractEvent<CandidateAddedEvent.InputTuple, CandidateAddedEvent.OutputTuple, CandidateAddedEvent.OutputObject>;
      CandidateAdded: TypedContractEvent<CandidateAddedEvent.InputTuple, CandidateAddedEvent.OutputTuple, CandidateAddedEvent.OutputObject>;
    

      'ElectionCreated(uint256,string)': TypedContractEvent<ElectionCreatedEvent.InputTuple, ElectionCreatedEvent.OutputTuple, ElectionCreatedEvent.OutputObject>;
      ElectionCreated: TypedContractEvent<ElectionCreatedEvent.InputTuple, ElectionCreatedEvent.OutputTuple, ElectionCreatedEvent.OutputObject>;
    

      'ElectionEnded(uint256)': TypedContractEvent<ElectionEndedEvent.InputTuple, ElectionEndedEvent.OutputTuple, ElectionEndedEvent.OutputObject>;
      ElectionEnded: TypedContractEvent<ElectionEndedEvent.InputTuple, ElectionEndedEvent.OutputTuple, ElectionEndedEvent.OutputObject>;
    

      'ElectionStarted(uint256)': TypedContractEvent<ElectionStartedEvent.InputTuple, ElectionStartedEvent.OutputTuple, ElectionStartedEvent.OutputObject>;
      ElectionStarted: TypedContractEvent<ElectionStartedEvent.InputTuple, ElectionStartedEvent.OutputTuple, ElectionStartedEvent.OutputObject>;
    

      'VoteCast(uint256,address,uint256)': TypedContractEvent<VoteCastEvent.InputTuple, VoteCastEvent.OutputTuple, VoteCastEvent.OutputObject>;
      VoteCast: TypedContractEvent<VoteCastEvent.InputTuple, VoteCastEvent.OutputTuple, VoteCastEvent.OutputObject>;
    

      'VoterRegistered(uint256,address)': TypedContractEvent<VoterRegisteredEvent.InputTuple, VoterRegisteredEvent.OutputTuple, VoterRegisteredEvent.OutputObject>;
      VoterRegistered: TypedContractEvent<VoterRegisteredEvent.InputTuple, VoterRegisteredEvent.OutputTuple, VoterRegisteredEvent.OutputObject>;
    
    };
  }